apiVersion: v1
kind: Secret
metadata:
  name: zksync-secrets
type: Opaque
data:
  L1_FAUCET_ADDRESS: {{ .Values.secrets.l1FaucetAddress | b64enc | quote }}
  L1_FAUCET_PRIVATE_KEY: {{ .Values.secrets.l1FaucetPrivateKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
