apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: zk-sync-run
  ports:
    - protocol: TCP
      port: 3052
      targetPort: 3052
  type: ClusterIP
