apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-run
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zk-sync-run
  template:
    metadata:
      labels:
        app: zk-sync-run
    spec:
      containers:
      - name: zk-sync-run
        image: "zk-sync-run:{{ .Values.image.runTag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3052
          name: http
        volumeMounts:
        - name: zksync-app-data
          mountPath: /app
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: zksync-app-data
