apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-init
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zk-sync-init
  template:
    metadata:
      labels:
        app: zk-sync-init
    spec:
      containers:
      - name: zk-sync-init
        image: "proviroll/zk-sync-init:{{ .Values.image.initTag }}"
        envFrom:
        - configMapRef:
            name: zksync-config
        - secretRef:
            name: zksync-secrets
        env:
        - name: SERVER_DB_URL
          value: "postgres://{{ .Values.postgresql.username }}:$(POSTGRES_PASSWORD)@{{ .Release.Name }}-postgres:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
        volumeMounts:
        - name: zksync-app-data
          mountPath: /app
      volumes:
      - name: zksync-app-data
        persistentVolumeClaim:
          claimName: zksync-app-data
